name: Bump git repository tag
description: Bumps patch part of the git tag

inputs:
  major-minor-version:
    description: "Major and minor version number, e.g. 1.2"
    required: true
  tag-bump-git-user-name:
    description: "Git user name to use for tagging"
    required: true
  tag-bump-git-user-email:
    description: "Git user email to use for tagging"
    required: true

outputs:
  version:
    description: "New version number after bumping. Corresponds to the tag."
    value: ${{ steps.bump-script.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: bump-script
      shell: bash
      run: |
        PREV_TAG=$(git describe --tags --abbrev=0 || echo "0.0.0")
        PREV_MAJOR_MINOR_VERSION=$(echo $PREV_TAG | cut -d. -f1-2)
        if [ "$PREV_MAJOR_MINOR_VERSION" != "${{ inputs.major-minor-version }}" ]; then
          echo "Major/Minor version changed, setting patch to 0"
          PATCH_VERSION='0'
        else
          echo "Bumping patch version"
          PATCH_VERSION=`echo $PREV_TAG | awk -F. '{OFS="."; $NF+=1; print $NF}'`
        fi
        VERSION="${{ inputs.major-minor-version }}.$PATCH_VERSION"

        git config user.name "${{ inputs.tag-bump-git-user-name }}"
        git config user.email "${{ inputs.tag-bump-git-user-email }}"

        git tag -a $VERSION -m "Automatic version bump"
        git push origin $VERSION

        echo "::set-output name=version::$VERSION"
