name: Bump git repository tag
description: Bumps patch part of the git tag

inputs:
  major_minor_version:
    description: "Major and minor version number, e.g. 1.2"
    required: true
  tag_bump_git_user_name:
    description: "Git user name to use for tagging"
    required: true
  tag_bump_git_user_email:
    description: "Git user email to use for tagging"
    required: true

outputs:
  version:
    description: "New version number after bumping. Corresponds to the tag."
    value: ${{ steps.bump-script.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: bump-script
      shell: bash
      run: |
        PREV_TAG=$(git describe --tags --abbrev=0 || echo "0.0.0")
        PREV_MAJOR_MINOR_VERSION=$(echo $PREV_TAG | cut -d. -f1-2)
        if [ "$PREV_MAJOR_MINOR_VERSION" != "$MAJOR_MINOR_VERSION" ]; then
          echo "Major/Minor version changed, setting patch to 0"
          PATCH_VERSION='0'
        else
          echo "Bumping patch version"
          PATCH_VERSION=`echo $PREV_TAG | awk -F. '{OFS="."; $NF+=1; print $NF}'`
        fi
        VERSION="${{ inputs.major_minor_version }}.$PATCH_VERSION"

        git config user.name ${{ inputs.tag_bump_git_user_name }}
        git config user.email ${{ inputs.tag_bump_git_user_email }}

        git tag -a $VERSION -m "Automatic version bump"
        git push origin $VERSION

        echo "::set-output name=version::$VERSION"
