name: Send slack notification
description: Bumps patch part of the git tag

inputs:
  status:
    description: "Success or fail message"
    required: true
  version:
    description: "Version of the software"
    required: false
  slack-webhook-url:
    description: "Slack webhook URL"
    required: true
  github-run-url:
    description: "URL to the GitHub run"
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

runs:
  using: "composite"
  steps:
    - shell: bash
      name: Slack notification
      if: ${{ inputs.status == 'success' }}
      run: |
        curl -f -d @- -H "Content-Type: application/json" "${{ inputs.slack-webhook-url }}" <<EOSLACKJSON
          {
            "attachments": [
              {
                "color": "#00FF00",
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "${{ github.event.repository.name }} (${{ inputs.version }}) - build succeeded",
                      "emoji": true
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Name:*\n${{ github.event.repository.name }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Triggered by:*\n${{ github.triggering_actor }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Version:*\n${{ inputs.version }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Ref:*\n${{ github.ref }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "<${{ inputs.github-run-url }}|View run>"
                    }
                  }
                ]
              }
            ]
          }
        EOSLACKJSON

    - shell: bash
      name: Slack notification failure
      if: ${{ inputs.status == 'failure' }}
      run: |
        curl -f -d @- -H "Content-Type: application/json" "${{ inputs.slack-webhook-url }}" <<EOSLACKJSON
          {
            "attachments": [
              {
                "color": "#FF0000",
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "${{ github.event.repository.name }} - build failed",
                      "emoji": true
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Commit message:*\n${{ github.event.head_commit.message }}"
                      },
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Name:*\n${{ github.event.repository.name }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Triggered by:*\n${{ github.triggering_actor }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Version:*\n${{ inputs.version }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Ref:*\n${{ github.ref }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "<${{ inputs.github-run-url }}|View run>"
                    }
                  }
                ]
              }
            ]
          }
        EOSLACKJSON
