name: Find next repository tag
description: Find next repository tag

inputs:
  major-minor-version:
    description: "Major and minor version number, e.g. 1.2"
    required: true
  tag-prefix:
    description: "Only look for tags with this prefix."
    required: false
    default: ''

outputs:
  version:
    description: "New version number after bumping. Corresponds to the tag."
    value: ${{ steps.find-next-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: find-next-version
      shell: bash
      run: |
        PREV_VERSION=$(git describe --tags --abbrev=0 --match "${{ inputs.tag-prefix }}*" --candidates 100 | sed -e "s/^${{ inputs.tag-prefix }}//" || echo "0.0.0")
        PREV_MAJOR_MINOR_VERSION=$(echo $PREV_VERSION  | cut -d. -f1-2)
        if [ "$PREV_MAJOR_MINOR_VERSION" != "${{ inputs.major-minor-version }}" ]; then
          echo "Major/Minor version changed, setting patch to 0"
          PATCH_VERSION='0'
        else
          echo "Bumping patch version"
          PATCH_VERSION=`echo $PREV_VERSION | awk -F. '{OFS="."; $NF+=1; print $NF}'`
        fi
        VERSION="${{ inputs.major-minor-version }}.$PATCH_VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
