name: Build and Push PIP Package

on:
  workflow_call:
    inputs:
      major-minor-version:
        description: "Major and minor version number, e.g. 1.2"
        required: true
        type: string
      production-ref:
        default: "refs/heads/master"
        required: false
        type: string

env:
  LIBRARIAN_URL: "http://librarian-service.backend.svc.cluster.local/v1/"

jobs:
  build-push-pip-package:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: python3 -m pip install wheel twine

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_CODEARTIFACT_ACCESS_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CODEARTIFACT_ACCESS_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS CodeArtifact Twine
        run: |
          aws codeartifact login --tool twine --repository ${{ secrets.CODEARTIFACT_REPO }} --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} --region ${{ secrets.AWS_REGION }}

      - name: Login to AWS CodeArtifact PIP
        run: |
          aws codeartifact login --tool pip --repository ${{ secrets.CODEARTIFACT_REPO }} --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} --region ${{ secrets.AWS_REGION }}

      - name: Install requirements
        run: python3 -m pip install -r requirements.txt

      - name: Test
        run: "[ -d \"tests\"] && python3 -m unittest discover -s ./tests"

      - uses: cacommodities/gha-shared/find-next-version@master
        id: find-next-version
        with:
          major-minor-version: ${{ inputs.major-minor-version }}

      - name: Build
        run: BUILD_VERSION= python3 setup.py sdist bdist_wheel

      - name: Push package
        if: ${{ github.ref == inputs.production-ref }}
        run: |
          BUILD_VERSION=${{ steps.find-next-version.outputs.version }} python3 setup.py sdist bdist_wheel
          python3 -m twine upload --skip-existing --repository codeartifact dist/*

      - if: ${{ github.ref == inputs.production-ref }}
        uses: cacommodities/gha-shared/push-git-tag@master
        id: push-git-tag
        with:
          tag: ${{ steps.find-next-version.outputs.version }}
          tag-bump-git-user-name: ${{ secrets.TAG_BUMP_GIT_USER_NAME }}
          tag-bump-git-user-email: ${{ secrets.TAG_BUMP_GIT_USER_EMAIL }}

      - name: Summary
        if: ${{ github.ref == inputs.production-ref }}
        run: |
          echo "### New version: ${{ steps.find-next-version.outputs.version }}" >> $GITHUB_STEP_SUMMARY

      - name: Slack notification
        if: ${{ success() || failure() }}
        uses: cacommodities/gha-shared/slack-notification@master
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          version: ${{ steps.find-next-version.outputs.version }}
          status: ${{ job.status }}
