name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      dockerfile:
        description: "Dockerfile to build"
        default: "Dockerfile"
        required: false
        type: string
      image-suffix:
        description: "Suffix to append to the image name"
        default: ""
        required: false
        type: string
      major-minor-version:
        description: "Major and minor version number, e.g. 1.2"
        required: true
        type: string
      production-ref:
        default: "refs/heads/master"
        required: false
        type: string

env:
  IMAGE_NAME: ${{ secrets.CR_URL }}/${{ github.event.repository.name }}${{ inputs.image-suffix }}

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_ACCESS_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create ECR repo if doesn't exist
        run: aws ecr create-repository --repository-name ${{ github.event.repository.name }} || true

      - name: Build image
        run: |
          docker pull $IMAGE_NAME:latest || true
          docker build -f ${{ inputs.dockerfile }} --cache-from ${{ env.IMAGE_NAME }}:latest -t ${{ env.IMAGE_NAME }}:latest .

      - if: ${{ github.ref == inputs.production-ref }}
        uses: cacommodities/gha-shared/bump-git-tag@master
        id: bump-git-tag
        with:
          major-minor-version: ${{ inputs.major-minor-version }}
          tag-bump-git-user-name: ${{ secrets.TAG_BUMP_GIT_USER_NAME }}
          tag-bump-git-user-email: ${{ secrets.TAG_BUMP_GIT_USER_EMAIL }}

      - name: Push image
        if: ${{ github.ref == inputs.production-ref }}
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:${{ steps.bump-git-tag.outputs.version }}
          docker push ${{ env.IMAGE_NAME }}:${{ steps.bump-git-tag.outputs.version }}
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Summary
        if: ${{ github.ref == inputs.production-ref }}
        run: |
          echo "### New version: ${{ steps.bump-git-tag.outputs.version }}" >> $GITHUB_STEP_SUMMARY

      - name: Slack notification
        uses: cacommodities/gha-shared/slack-notification@master
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          version: ${{ steps.bump-git-tag.outputs.version }}
