name: Build and Push NuGet Package

on:
  workflow_call:
    inputs:
      proj-path:
        description: "Path to the project to pack"
        required: true
        type: string
      tag-prefix:
        description: "Prefix to prepend to the tag which makes version bump independent."
        required: false
        type: string
        default: ""
      major-minor-version:
        description: "Major and minor version number, e.g. 1.2"
        required: true
        type: string
      production-ref:
        default: "refs/heads/master"
        required: false
        type: string

jobs:
  build-push-nuget-package:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.302'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_CODEARTIFACT_ACCESS_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CODEARTIFACT_ACCESS_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS CodeArtifact Nuget
        # https://github.com/aws/aws-cli/issues/7328
        run: |
          dotnet nuget list source --format detailed && \
          aws codeartifact login --tool dotnet --repository ${{ secrets.CODEARTIFACT_REPO }} --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} --region ${{ secrets.AWS_REGION }}

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build

      - uses: cacommodities/gha-shared/find-next-version@master
        id: find-next-version
        with:
          major-minor-version: ${{ inputs.major-minor-version }}
          tag-prefix: ${{ inputs.tag-prefix }}

      - name: Push package
        if: ${{ github.ref == inputs.production-ref }}
        run: |
          dotnet pack ${{ inputs.proj-path }} -c Release -p:PackageVersion=${{ steps.find-next-version.outputs.version }}
          dotnet nuget push "${{ inputs.proj-path }}/bin/Release/*.nupkg" --source ${{ secrets.CODEARTIFACT_DOMAIN }}/${{ secrets.CODEARTIFACT_REPO }}

      - if: ${{ github.ref == inputs.production-ref }}
        uses: cacommodities/gha-shared/push-git-tag@master
        id: push-git-tag
        with:
          tag: "${{ inputs.tag-prefix }}${{ steps.find-next-version.outputs.version }}"
          tag-bump-git-user-name: ${{ secrets.TAG_BUMP_GIT_USER_NAME }}
          tag-bump-git-user-email: ${{ secrets.TAG_BUMP_GIT_USER_EMAIL }}

      - name: Summary
        if: ${{ github.ref == inputs.production-ref }}
        run: |
          echo "### New version: ${{ steps.find-next-version.outputs.version }}" >> $GITHUB_STEP_SUMMARY

      - name: Slack notification
        if: ${{ success() || failure() }}
        uses: cacommodities/gha-shared/slack-notification@master
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          version: ${{ steps.find-next-version.outputs.version }}
          status: ${{ job.status }}
