name: build-push-nuget-package

on:
  workflow_call:
    inputs:
      proj_path:
        description: 'Path to the project to pack'
        required: true
        type: string
      major_minor_version:
        description: "Major and minor version number, e.g. 1.2"
        required: true
        type: string
      production_ref:
        default: "refs/heads/master"
        required: false
        type: string

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CODEARTIFACT_ACCESS_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CODEARTIFACT_ACCESS_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS CodeArtifact Nuget
        run: |
          aws codeartifact login --tool dotnet --repository ${{ secrets.CODEARTIFACT_REPO }} --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} --region ${{ secrets.AWS_REGION }}

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build

      - if: ${{ github.ref == inputs.production_ref }}
        uses: cacommodities/gha-shared/bump-git-tag@master
        id: bump-git-tag
        with:
          major_minor_version: ${{ inputs.major_minor_version }}
          tag_bump_git_user_name: ${{ secrets.TAG_BUMP_GIT_USER_NAME }}
          tag_bump_git_user_email: ${{ secrets.TAG_BUMP_GIT_USER_EMAIL }}

      - name: Push package
        if: ${{ github.ref == inputs.production_ref }}
        run: |
          dotnet pack ${{ env.PROJ_PATH }} -c Release -p:PackageVersion=${{ env.VERSION }}
          dotnet nuget push "${{ env.PROJ_PATH }}/bin/Release/*.nupkg" --source ${{ secrets.CODEARTIFACT_DOMAIN }}/${{ secrets.CODEARTIFACT_REPO }}

      - name: Summary
        if: ${{ github.ref == inputs.production_ref }}
        run: |
          echo "### New version: ${{ steps.bump-git-tag.outputs.version }}" >> $GITHUB_STEP_SUMMARY

      - name: Slack notification
        uses: cacommodities/gha-shared/slack-notification@master
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          version: ${{ steps.bump-git-tag.outputs.version }}
